# config.yaml

# Parameters for new_main.py
# Configuration file for TireSoundProcessor
# Contains parameters for signal processing and rise point detection

new_main:
  # Default noise threshold for regular (non-standalone) processing
  # Used in Processed and Processed_Trimmed directories
  noise_threshold: 0.03

  # Intensity thresholds for pulse analysis
  # Used to detect different levels of signal intensity
  # Higher values detect stronger parts of the pulse
  intensity_thresholds: [0.5, 0.7, 0.8, 0.9]

  # Number of dimensions to include after detecting rise point
  # Determines how much of the signal to analyze after the first rise
  selected_dims_after_rise_point: 32

  # Parameters for dynamic noise threshold in standalone processing:

  # Number of initial points used to establish baseline noise level
  # Larger values provide more stable baseline but might include signal
  # Recommended range: 5-20 points
  baseline_window_size: 10

  # Multiplier for standard deviation in threshold calculation
  # Higher values make detection more conservative
  # Recommended range: 2.0-5.0
  std_dev_multiplier: 3.0

  # Minimum threshold as percentage of signal range
  # Helps prevent false detections in very quiet segments
  # Lower values are more sensitive to small changes
  # Recommended range: 0.001-0.05 (0.1%-5%)
  min_threshold_percentage: 0.001

  # Number of consecutive points required above threshold
  # to confirm a sustained rise
  # Higher values reduce false positives but might miss quick rises
  # Recommended range: 2-5 points
  sustained_rise_points: 3

  # Future parameters can be added here with appropriate documentation

# Parameters for new_visualizer.py
new_visualizer:
  hitting_type: Both  # Options: Tread, Side, Both
