# config.yaml

# Parameters for pulse_width_calculator.py
# Configuration file for TireSoundProcessor
# Contains parameters for signal processing and rise point detection

pulse_width_calculator:
  # Default noise threshold for regular (non-standalone) processing
  # Used in Processed and Processed_Trimmed directories
  noise_threshold: 0.03

  # Intensity thresholds for pulse analysis
  # Used to detect different levels of signal intensity
  # Higher values detect stronger parts of the pulse
  intensity_thresholds: [0.5, 0.7, 0.8, 0.9]

  # Number of dimensions to include after detecting rise point
  # Determines how much of the signal to analyze after the first rise
  selected_dims_after_rise_point: 32

  # Parameters for dynamic noise threshold in standalone processing:

  # Number of initial points used to establish baseline noise level
  # Recommended range: 5-20 points
  baseline_window_size: 10

  # Multiplier for standard deviation in threshold calculation
  # Recommended range: 2.0-5.0
  std_dev_multiplier: 5.0

  # Minimum threshold as percentage of signal range
  # Recommended range: 0.001-0.05 (0.1%-5%)
  min_threshold_percentage: 0.05

  # Number of consecutive points required above threshold
  # Recommended range: 2-5 points
  sustained_rise_points: 3

  # Number of points to look back when checking for gradual rises
  # Higher values detect more gradual rises but may include noise
  # Recommended range: 2-5 points
  lookback_window_size: 3

# Parameters for new_visualizer.py
new_visualizer:
  hitting_type: Both  # Options: Tread, Side, Both
