# Configuration file for TireSoundProcessor
# Contains parameters for both mounted and standalone tire signal processing

pulse_width_calculator:
  # Common parameters shared between mounted and standalone processing
  intensity_thresholds: [0.5, 0.7, 0.8, 0.9]  # Thresholds for pulse analysis at different intensity levels

  # Parameters for mounted tire processing
  mounted:
    # Signal trimming configuration
    trim_signal: true
    trim_dims_after_rise: 32

    # Fixed noise threshold for mounted tire signal
    noise_threshold: 0.01                  # Noise threshold for mounted tire signal

  # Parameters for standalone tire processing
  standalone:
    # Signal trimming configuration
    trim_signal: true
    trim_dims_after_rise: 32

    # Dynamic noise threshold parameters
    baseline_window_size: 2
    std_dev_multiplier: 2.0
    min_threshold_percentage: 0.05
    sustained_rise_points: 4
    lookback_window_size: 2

    # Baseline subtraction configuration
    baseline_subtraction_method: "adaptive" # Baseline subtraction method for standalone tire signal (none, fixed, adaptive)
    fixed_baseline_value: 0.01

    # Adaptive baseline parameters
    baseline_computation: "median"        # Baseline computation method (mean, median)
    sliding_window_min_size: 5
    sliding_window_max_size: 20
    quietness_metric: "std"              # Metric for quietness (std, mad)

    # Volatility handling parameters
    volatility_threshold: 0.5
    high_volatility_percentile: 75
    low_volatility_percentile: 25
    max_threshold_factor: 0.3