pulse_width_calculator:
  directories:
    input_dir: "/Users/jothamwambi/Projects/tire_pressure_analysis/Pulse_Width_Analysis/Data/Mounted/Processed_CSV_Files(abcd@10_SideStrong-Best)"
    standalone_dir: "/Users/jothamwambi/Projects/tire_pressure_analysis/Pulse_Width_Analysis/Merged"
    output_dir: "."
    output_mounted_subdir: "Processed_Mounted(abcd@10_SIDEStrong-Best)"
    output_standalone_subdir: "Processed_Standalone"

  # Common parameters shared between mounted and standalone processing
  common:
    intensity_thresholds: [0.5, 0.7, 0.8, 0.9]  # Thresholds for pulse analysis

  # Parameters for mounted tire processing
  mounted:
    # Signal detection parameters
    noise_threshold: 0.001  # Base threshold for signal detection
    noise_detection_method: "dynamic"  # Options: "dynamic", "fixed"
    
    # Signal trimming configuration
    trim_signal: true
    trim_dims_after_rise: 32

    # Dynamic noise threshold parameters
    baseline_window_size: 2
    std_dev_multiplier: 2
    min_threshold_percentage: 0.05
    sustained_rise_points: 4
    lookback_window_size: 2

    # Baseline subtraction configuration
    baseline_subtraction_method: "none"  # Options: "none", "fixed", "adaptive"
    fixed_baseline_value: 0.02
    
    # Adaptive baseline parameters
    baseline_computation: "median"  # Options: "mean", "median"
    sliding_window_min_size: 5 
    sliding_window_max_size: 20
    quietness_metric: "std"  # Options: "std", "mad", "mix"

    # Volatility handling parameters
    volatility_threshold: 0.5
    high_volatility_percentile: 75
    low_volatility_percentile: 25
    max_threshold_factor: 0.3

  # Parameters for standalone tire processing
  standalone:
    # Signal detection parameters
    noise_threshold: 0.001  # Base threshold for signal detection
    noise_detection_method: "dynamic"  # Options: "dynamic", "fixed"
    
    # Signal trimming configuration
    trim_signal: true
    trim_dims_after_rise: 32

    # Dynamic noise threshold parameters
    baseline_window_size: 2
    std_dev_multiplier: 2
    min_threshold_percentage: 0.05
    sustained_rise_points: 4
    lookback_window_size: 2

    # Baseline subtraction configuration
    baseline_subtraction_method: "fixed"  # Options: "none", "fixed", "adaptive"
    fixed_baseline_value: 0.03

    # Adaptive baseline parameters
    baseline_computation: "median"  # Options: "mean", "median"
    sliding_window_min_size: 5
    sliding_window_max_size: 20
    quietness_metric: "std"  # Options: "std", "mad", "mix"

    # Volatility handling parameters
    volatility_threshold: 0.5
    high_volatility_percentile: 75
    low_volatility_percentile: 25
    max_threshold_factor: 0.3